### ISSUE TITLE
Page is lack of meta for rendering on Twitter

### ISSUE THREAD

**Issue by tisonkun** [engula/engula.github.io#18]
For example, https://twitter.com/engulaio/status/1471743304433692674

**Comment by tisonkun** [comment]
I think these metadata is required:

* `<meta name="twitter:card" content="...">`
* `<meta name="twitter:image" content="...">`

We can investigate how to achieve with mkdocs or just replace with a full-featured website framework.

**Comment by huachaohuang** [comment]
I actually tried [Docusaurus](https://docusaurus.io/) before. But it's too complicated than I expected. So I decided to use Mkdocs instead. However, if anyone can help to set it up and it works nicely, I am very OK with it.
