### ISSUE TITLE
Find a flexible website framework to publish Engula site

### ISSUE THREAD

**Issue by tisonkun** [engula/engula.github.io#19]
Original requirements can come from:

* https://github.com/engula/engula/discussions/184
* https://github.com/engula/engula.github.io/issues/18

**Comment by tisonkun** [comment]
For "Contributor Medal Wall" I'm assuming a page like [Apache SkyWalking Team](https://skywalking.apache.org/team/), but encourage contributors to identify themselves with user generated content instead of totally autogenerated ones.

**Comment by juzhiyuan** [comment]
Content is more important than UI in my opinion 😄 I still would prefer using Docusaurus to build the website.

**Comment by juzhiyuan** [comment]
For the team page, could also see https://apisix.apache.org/team

**Comment by tisonkun** [comment]
@juzhiyuan thanks for your insights! I agree content over UI. The issue here is aimed at UI/framework however. We're not in a hurry and I'm open to do some investigations before ordering contents. Maybe finally docu is the best choice with trade-offs.

BTW, the page you share is broken on my laptop and here is the issue https://github.com/apache/apisix/issues/5860.

**Comment by juzhiyuan** [comment]
noted 😄
