### ISSUE TITLE
Consistently use GitHub icon?

### ISSUE THREAD

**Issue by tisonkun** [engula/engula.github.io#6]
![image](https://user-images.githubusercontent.com/18818196/136131579-70d52bc4-dc82-4590-89d3-698912b6f863.png)

This icon is `fontawesome/brands/git-alt` instead of `fontawesome/brands/github` that used in the extra/social section.

I don't know whether or not we should keep consistency on icon usages.

cc @huachaohuang

**Comment by tisonkun** [comment]
To be visualized, I mean change the icon to

![image](https://user-images.githubusercontent.com/18818196/136131888-6416f3e4-f1d8-44a3-8b15-7c60e07df62b.png)

**Comment by huachaohuang** [comment]
Well, either one works for me. But I am glad to make them consistent too :)

**Comment by tisonkun** [comment]
@huachaohuang Get it and here is #7 .
